"""update table_log column new_value

Revision ID: 00d1fcaffdaa
Revises: 560245253d2a
Create Date: 2022-06-27 11:12:24.543834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d1fcaffdaa'
down_revision = '560245253d2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('log_project_id_fkey', 'log', type_='foreignkey')
    op.drop_constraint('log_table_id_fkey', 'log', type_='foreignkey')
    op.drop_constraint('log_manager_id_fkey', 'log', type_='foreignkey')
    op.create_foreign_key(None, 'log', 'manager', ['manager_id'], ['id'], source_schema='core', referent_schema='core', ondelete='CASCADE')
    op.create_foreign_key(None, 'log', 'tables', ['table_id'], ['id'], source_schema='core', referent_schema='core', ondelete='CASCADE')
    op.create_foreign_key(None, 'log', 'project', ['project_id'], ['id'], source_schema='core', referent_schema='core', ondelete='CASCADE')
    op.drop_constraint('tables_project_id_fkey', 'tables', type_='foreignkey')
    op.create_foreign_key(None, 'tables', 'project', ['project_id'], ['id'], source_schema='core', referent_schema='core', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tables', schema='core', type_='foreignkey')
    op.create_foreign_key('tables_project_id_fkey', 'tables', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'log', schema='core', type_='foreignkey')
    op.drop_constraint(None, 'log', schema='core', type_='foreignkey')
    op.drop_constraint(None, 'log', schema='core', type_='foreignkey')
    op.create_foreign_key('log_manager_id_fkey', 'log', 'manager', ['manager_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('log_table_id_fkey', 'log', 'tables', ['table_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('log_project_id_fkey', 'log', 'project', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
